name: Test dataset

on:
  push: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
          cache: npm
      - run: npm ci
      - run: npm test
